// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSqmdFz9zvBvsuUgGibNISsZbytBpkosk',
    appId: '1:664656667434:web:91781508f76e8aab48b453',
    messagingSenderId: '664656667434',
    projectId: 'app-smsvx',
    authDomain: 'app-smsvx.firebaseapp.com',
    storageBucket: 'app-smsvx.appspot.com',
    measurementId: 'G-QKCW30LH6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoKx3tgabADzggx7OdblDtDGMARAG_tMc',
    appId: '1:664656667434:android:a25f8103a064ac0248b453',
    messagingSenderId: '664656667434',
    projectId: 'app-smsvx',
    storageBucket: 'app-smsvx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrJSKNnWQ-dG3qki-SFR8PiXVHpDV2ipI',
    appId: '1:664656667434:ios:bb34146ee3122fce48b453',
    messagingSenderId: '664656667434',
    projectId: 'app-smsvx',
    storageBucket: 'app-smsvx.appspot.com',
    iosBundleId: 'com.example.flutterDrawergit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrJSKNnWQ-dG3qki-SFR8PiXVHpDV2ipI',
    appId: '1:664656667434:ios:442e75b38b752eeb48b453',
    messagingSenderId: '664656667434',
    projectId: 'app-smsvx',
    storageBucket: 'app-smsvx.appspot.com',
    iosBundleId: 'com.example.flutterDrawergit.RunnerTests',
  );
}
